### ISSUE TITLE
Locally Linked modules resolve incorrectly

### ISSUE THREAD

**Issue by tamoore** [seek-oss/seek-style-guide-webpack#10]
I wanted to get the ball rolling around discussing this problem.
 
In my opinion, it's better to have the consumer resolve the style guide path and pass it as a required property to this module.

Thoughts?

**Comment by markdalgleish** [comment]
Could you post an example of what you think the API would look like in this case?

**Comment by tamoore** [comment]
Something like:

```javascript
decorate<Client|Server>Config(config: WebpackConfig, styleGuidePath: string, options?: Options)
```

**Comment by markdalgleish** [comment]
If you remove the style guide from dev dependencies, does require.resolve end up resolving the style guide from your project's node modules?

**Comment by tamoore** [comment]
Not when it's linked locally. 

```
Compile: started
>> Build client package
module.js:472
    throw err;
    ^

Error: Cannot find module 'seek-style-guide'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.resolve (internal/module.js:27:19)
    at Object.<anonymous> (/Users/tmoore/projects/seek/packages/seek-style-guide-webpack/index.js:10:45)
    at Module._compile (module.js:571:32)
    at loader (/Users/tmoore/projects/seek/packages/seek-chalice/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/tmoore/projects/seek/packages/seek-chalice/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)```

**Comment by tamoore** [comment]
I wonder whether maybe there is a solution that if not passed the path explicitly it'll try to resolve it and if it fails give a nice error message that explains the issue.

**Comment by markdalgleish** [comment]
I'm more in favour of something along those lines. This is such an edge case, I'd prefer to keep it out of the API if we can.

**Comment by tamoore** [comment]
It could be an addition to the options?
 
I think we should also wrap where we try to resolve extra included paths in a try catch that can message that they have to be node modules. I actually got tripped up on that one, and it was only when I looked at the source that I realised why it was failing.

**Comment by markdalgleish** [comment]
Did some digging, there might be a way out: https://stackoverflow.com/questions/25684309/npm-peerdependencies-during-development/25800501#25800501

**Comment by tamoore** [comment]
So the current API on `require` doesn't include `require.main.resolve`. In fact, it really only allows you to get a map of the current module (i.e. main module ran with node) its children and its ancestor tree. https://nodejs.org/api/modules.html#modules_require

That makes sense from a security POV to me.

So, what does that mean? Well, when you run it linked locally, you can determine that it's not the main module. Check. good.

But, determining the correct path of the main modules' `node_modules` folder is not as simple. 

We are essentially presented with an array like the following:

```javascript
[ '/Users/tmoore/projects/seek/packages/seek-chalice/node_modules/webpack/bin/node_modules',
  '/Users/tmoore/projects/seek/packages/seek-chalice/node_modules/webpack/node_modules',
  '/Users/tmoore/projects/seek/packages/seek-chalice/node_modules',
  '/Users/tmoore/projects/seek/packages/node_modules',
  '/Users/tmoore/projects/seek/node_modules',
  '/Users/tmoore/projects/node_modules',
  '/Users/tmoore/node_modules',
  '/Users/node_modules',
  '/node_modules' ]
```

I think we are getting into possibly indeterminate land here. As which node_module folder out of the list above is the canonical one we are concerned with?

 I come back to the original proposition that allowing a consumer at least the option to specify the `seek-style-guide` path explicitly is probably the best approach here.
